spring.application.name=backend
# Po??czenie z baz? danych
spring.datasource.url=jdbc:postgresql://localhost:5432/bezpieczny_menedzer
spring.datasource.username=postgres
spring.datasource.password=Kwakwa5!

# Automatyczne tworzenie i aktualizowanie tabel na podstawie kodu Javy
spring.jpa.hibernate.ddl-auto=update

# Wy?wietlanie zapyta? SQL w konsoli (przydatne przy szukaniu b??dów)
spring.jpa.show-sql=true